services:
  - type: web
    name: BLADE-MD-V2
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
        sync: false
      - key: SUDO
        sync: false
