services:
  - type: web
    name: BLADE-MD-V2
    env: docker
    branch: main
    dockerfilePath: Dockerfile
    repo: https://github.com/Louks000123/NARUTO-MD.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
